// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa6bILXg7-qezj4BAWNcFqfopbg1WS6Dg',
    appId: '1:153503407929:web:c5ed053ff6f68bf1ecd2e8',
    messagingSenderId: '153503407929',
    projectId: 'darshan-m-s',
    authDomain: 'darshan-m-s.firebaseapp.com',
    storageBucket: 'darshan-m-s.firebasestorage.app',
    measurementId: 'G-57B41M76XQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXJpz2il1SKBKSCsbIlqubHpNzzM9bThY',
    appId: '1:153503407929:android:aaa0128964cd0864ecd2e8',
    messagingSenderId: '153503407929',
    projectId: 'darshan-m-s',
    storageBucket: 'darshan-m-s.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmWAyMoo7YysIMHEl8xfPXEXQaca8dXRA',
    appId: '1:153503407929:ios:e52560f1c8d75142ecd2e8',
    messagingSenderId: '153503407929',
    projectId: 'darshan-m-s',
    storageBucket: 'darshan-m-s.firebasestorage.app',
    iosBundleId: 'com.example.darshanPortfolio',
  );
}
